name: Deploy Klavion to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Setup Ruby for Sass
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      
      - name: Install Sass
        run: gem install sass
      
      - name: Build CSS
        run: |
          mkdir -p scss
          if [ -f scss/styles.scss ]; then
            sass scss/styles.scss scss/styles.min.css --style=compressed
          else
            echo "SCSS file not found, skipping CSS build"
          fi
      
      - name: Prepare deployment files
        run: |
          # Remove node_modules and other unnecessary files for deployment
          rm -rf node_modules
          rm -rf coverage
          rm -rf tests
          rm -rf .git
          rm -f package-lock.json
          rm -f *.log
          echo "Deployment files prepared"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4